language: java
env:
  global:
    - # ^^ OSSRH_USERNAME
    -   secure: "Nm0Jo/K2fxnsdPuzVfJbQPsXsiUsY1HVeDQXrLOWe/JW80UEY0PEfIoXYdRXDGqmfdREDZLfCvYgRsGekZd4/q3eIEPirzicjZQ58airKtmsRy1Kr1CIQnpRQXfbO45FXGYI7puDWdr+O17wJ2OMPMx0hRZj2kHqTj5IZYJjQrv2uEcevOPbTPBEHhDOedfvoBUlcD5eaquC3wO45RW4d43BCu1m/n16tYrfrq96hr4E0G5Llj/aMQ5inkUJ6G/TnNb0XcRGuzKp9cMSXAnwtSinL0MfFGYHGshApY5ufb8qKaGQYcjyJcoxzIWaQt+t5feTvOYORSVPnuTEsj+GDiN0flkvDW58007FuE3OEAE2ebVhQl6rX+BFKazR4Dcouyli5wULuF84ztEWCuu7bGkOP0pvWLp6a3vsmNDGwG4Nq9wT7amusbFdTzjhHlEbHjMhnuE6ptHf0856O7jH8vqRM6SlQVBj7qumLOat9XQX65QPd+u0NTMhHU87JMpT7P5gUrHerqknkdQ+VnIQ0HmC622CCUDhaG7WukjiM+eoh3cAl5S/Wnb6waZ5fVE46fKvKreKnTQnjkSViltCh0SxxZxtjd4nyMmxgtQFophq6D7kqPxfv9BV67RSb7ObizgkCuOogNp6kzcwa8Wi2yXL+rj72pwxs1Sn/Rhs5fw="
    - # ^^ OSSRH_PASSWORD
    - secure: "rM6PwQ6HfVQp1EH/Z2w507Lys/bm59pyR6h5TEF/CkLFZrjI8rRE0uJAZMT0PzUOnjLDMrh1yzEmqI0orN6a3CYLPfjmaQ82I4UDdgU81lwtzJGq7bCRlUYiEZw5ZRqvYDvGW/LJVG2m/6p5aAtGqcDmvpeuyEsq+zlPw4AcXKXcewLQIJBpTG1jdEj8EtnZrmkJgalBD1XCBXTGNRGCNnLgz60qvfOL4iUpfxbnmGhpOmypPhDzszKzxXuADJVtuPqzGu3d21MsdRhmMo5uvnOWO0j0LFYHgZWjp+ZFCk9rEbFq52sEE7S/jClya3yvkrMAvnbLPuCB3ycG4x0y33s4h7F/tJussopAHHSsrEptZqhQcz6xWLeoq76Fen+RzLmEm77Bvbh/tv2r8ZnV6Rwr3u/zwqmZIjM9taauET2L5tKdU9E+3vxFGSSd+mTnRPSeDArdGDcIkVKXG1+vWkdDsVQkuSfv6qTpwmWZNBTBT6liOSBaV/j0UQ719tjR5+oyd7qXzqw6KplibhryJrihyYTaXocvInXWfOUZlMJk09FNjj2cvyH1yObE76jNEUVy4gdDoqSY94lRwKzCFj19uOlmzbhxaUjUdy1tfYBTbaWvtCp19N8REaGBxqk25A2iMhOO4yaa3z49d9Kvl0WeG24ZFe9ST5PxjvNxaWE="
    - # ^^ GPG_KEY_NAME
    - secure: "viqUnk6pU6Qn1THmTUBqrJa4G4TKS/ZxhvTHuW12EmGG033c6LDt6X1yn05iosLgGqZkRO06ipn8eriOoxIVAgNo3yCdMtRztjdyDbM4RJmjPrn6ra1H/0Elq0luLoxyDmP3Kfzm/GesCfosTfXV1lrVHq1VeDrlJ5RrXnFh4HNz8zoU8XHX7ZnDaWj47ujEfuRBLz4pjqEggTf8CgnvjQ5Th65krQprmD/T2+rC6N68yvIlEOX8LFipzei943JysYJPBj7eksIVGXpH0ZNvIFTpKZP8CNI1oDq/PCTYIFmlEOh0nGdhk6xJS8ZLK2lglYycCmXDEPcgjLZdjrW+Pi/5pkxib1uCjBMG28fFq2G5aDHsEFWplGyPIexXRooKMxMMQyjJgrm3MFX6cnLdNYIaJDg/K6LxMxbkaBhCEdmFjZsYB6O0hnfnysefKu5xcvQQ0JxIAeYJkTffFtPvXVgPiWwZiUUTJC3/KDLWDdWKXo9izZhmulLwOUxshlaEMao0yO1nAzQXx/V8Z8EFso8SaN/eULPlQHkYt2w1LwBXlG73MZ/VAw+B9+gQrN/35GDxxCG/cY3bwquFAtzhWjz/23w9OcmNUORcE1dWmPNjcd9o4X0Ub1S77MYNKCOCpGsyfjz7wnxG8eJ1X/L8Yu1W0UDGJIkjp9uTDunEnNI="
    - # ^^ GPG_PASSPHRASE
    - secure: "M0yb9YgQAvtAFg4+QVXeHrVx/83TJVx+SFMoMp9qVYTqcgYFhMOWTAJ6AHx0yDH1FNiFPc3nHjhwf3jV735MZSV13oOCCRtMulwGip61IRHNGxfB4fNFyo0syTuRglj9Oornxatcs6xRLPClNv+TWemI09Hjbhcc6EXcEfjq2kX/JI3gYhl22sSvpbm4dff8VAd/YJj4beupHxfCAE0uCaihLQCvI5X/lwBy4lIE+u1QvKpmZ8ePNtuWO3SZkabGnI71jB72XomfziTJk0B59kJ57EQ3RRU3QBLou972OiXf4xEQ2H9k7jHU+jbZ9Sj3tYmikWvF2FTARO+2UXScPGSxP0prCVV3NKqkdQGLprrGCdSoKrGYyNvmbmzxPxnl49u1IdxksGxtPE54aTRd+mGNTQAVhjynpdsmFqgE+Lpmkq6Lyxy21mAoyR/+GBCzTz7fKGfj++olgnauEmUxdXyMgW8t+9QHBV2Ht2gXh1hppqk1HUPaejtL4VZhf8uxRZZ4MMXmbKUWBmgC4QOhKNJftd5AifFe5xI0l+qZ1bTC3k+v4IJphV1Td6Cyy3FkXVDJ8dJW9ijaeDFkTNHkAHYcbwmG9WqywB6dW4F5J0JU68U5gLYFgqcKb637YWGWQdpvSxowq97pIvmhr570jCIf8oH2uNFaV5st8mp353c="
before_install:
  - openssl aes-256-cbc -K $encrypted_7581aabc6032_key -iv $encrypted_7581aabc6032_iv -in codesigning.asc.enc -out codesigning.asc -d
  - gpg --yes --batch --import codesigning.asc
jdk:
  - oraclejdk8
install: mvn clean install -P !ossrh -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
script:
- mvn deploy -P ossrh --settings mvnsettings.xml
cache:
  directories:
    - ~/.m2/repository
branches:
  only:
    - master
    - develop
    - /^feature.*/
    - /^hotfix.*/
notifications:
  email:
    on_success: change
    on_failure: change
after_failure:
  - find . -size +1k -regex  ".*/surefire-reports/.*\.txt" -exec cat {} +
