name: Test
on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    name: Test and Sign
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Test
        run: mvn -B test
